import type { INodeProperties } from 'n8n-workflow';

const locatorOperations = [
	'fill',
	'selectOption',
	'check',
	'uncheck',
	'getText',
	'getAttribute',
	'uploadFile',
];

const roleOptions = [
	{ name: 'ボタン', value: 'button' },
	{ name: 'チェックボックス', value: 'checkbox' },
	{ name: 'コンボボックス', value: 'combobox' },
	{ name: '見出し', value: 'heading' },
	{ name: '画像', value: 'img' },
	{ name: 'リンク', value: 'link' },
	{ name: 'リスト項目', value: 'listitem' },
	{ name: '選択肢', value: 'option' },
	{ name: 'ラジオボタン', value: 'radio' },
	{ name: 'タブ', value: 'tab' },
	{ name: 'テキストボックス', value: 'textbox' },
];

const resolvedLocatorTypes = ['role', 'label', 'placeholder', 'text', 'testId', 'css', 'xpath'];

function locatorFields(
	displayOptions: NonNullable<INodeProperties['displayOptions']>,
	roleDisplayName = '画面部品の種類',
): INodeProperties[] {
	return [
		{
			displayName: '操作する場所の指定方法',
			name: 'locatorType',
			type: 'options',
			default: 'picker',
			displayOptions,
			options: [
				{
					name: 'CSSで指定（上級者向け）',
					value: 'css',
					description: 'HTMLのCSSセレクターで指定します',
				},
				{
					name: 'XPathで指定（上級者向け）',
					value: 'xpath',
					description: 'HTMLのXPathで指定します',
				},
				{
					name: 'テストIDで指定（上級者向け）',
					value: 'testId',
					description: 'HTMLのdata-testid属性で指定します',
				},
				{
					name: 'ブラウザで選ぶ（おすすめ）',
					value: 'picker',
					description: 'ブラウザで対象を選び、指定方法と値を自動で設定します',
				},
				{
					name: '画面の部品名で指定',
					value: 'role',
					description: 'ボタンやリンクなどの種類と画面上の名前で指定します',
				},
				{
					name: '項目名で指定',
					value: 'label',
					description: '氏名や電話番号など、入力欄の項目名で指定します',
				},
				{
					name: '入力欄の案内文で指定',
					value: 'placeholder',
					description: '入力欄の中に薄く表示されている案内文で指定します',
				},
			],
		},
		{
			displayName: 'ブラウザで操作する場所を選ぶ',
			name: 'elementPicker',
			type: 'button',
			default: '',
			description:
				'別のブラウザで目的の画面まで移動し、Altキーを押しながら対象をクリックします。選択後、指定方法と値を自動で設定します。',
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: ['picker'],
				},
			},
			typeOptions: {
				buttonConfig: {
					label: 'ブラウザを開いて選ぶ',
					action: {
						type: 'invokeNodeAction',
						handler: 'pickElement',
						targets: {
							locatorType: 'locatorType',
							locatorValue: 'locatorValue',
							locatorRole: 'locatorRole',
							locatorName: 'locatorName',
							pickerLocatorVariants: 'pickerLocatorVariants',
							iframePath: 'iframePath',
						},
					},
				},
			},
		},
		{
			displayName: roleDisplayName,
			name: 'locatorRole',
			type: 'options',
			default: 'button',
			options: roleOptions,
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: ['role'],
				},
			},
		},
		{
			displayName: '画面に表示されている名前',
			name: 'locatorName',
			type: 'string',
			default: '',
			required: true,
			placeholder: '登録、検索、ログインなど',
			description: 'ボタンやリンクに表示されている文字。アイコンだけの場合は代替名を指定します',
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: ['role'],
				},
			},
		},
		{
			displayName:
				'この指定方法は複数の要素に一致しやすいため、新しい設定では利用できません。「ブラウザで選ぶ」を選び、対象を選択し直してください。',
			name: 'legacyTextLocatorNotice',
			type: 'notice',
			default: '',
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: ['text'],
				},
			},
		},
		{
			displayName: '探す文字または指定値',
			name: 'locatorValue',
			type: 'string',
			default: '',
			required: true,
			placeholder: '氏名、検索、#customer-nameなど',
			description: '選んだ指定方法に合わせて、項目名、案内文、またはHTMLの指定値を入力します',
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: ['label', 'placeholder', 'text', 'testId', 'css', 'xpath'],
				},
			},
		},
		{
			displayName: '埋め込み画面（IFrame）',
			name: 'iframePath',
			type: 'fixedCollection',
			placeholder: 'IFrameを追加',
			default: {},
			typeOptions: { multipleValues: true, sortable: true },
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: resolvedLocatorTypes,
				},
			},
			description: '通常は追加不要です。IFrame内を操作する場合は、外側のIFrameから順番に追加します',
			options: [
				{
					displayName: 'IFrame',
					name: 'iframe',
					values: [
						{
							displayName: 'IFrameの見つけ方',
							name: 'frameType',
							type: 'options',
							default: 'name',
							options: [
								{ name: 'CSSで指定（上級者向け）', value: 'css' },
								{ name: 'URLの一部で指定', value: 'url' },
								{ name: '名前で指定（おすすめ）', value: 'name' },
							],
						},
						{
							displayName: 'IFrameの指定値',
							name: 'frameValue',
							type: 'string',
							default: '',
							required: true,
							placeholder: 'customer-frameなど',
							description: '選んだ見つけ方に合わせて、名前、URLの一部、またはCSSを入力します',
						},
					],
				},
			],
		},
	];
}

const retryFields: INodeProperties[] = [
	{
		displayName: '一時的な失敗を自動で再試行',
		name: 'retry',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '再試行する回数',
		name: 'maxRetries',
		type: 'number',
		default: 2,
		typeOptions: { minValue: 1, maxValue: 5 },
		displayOptions: { show: { retry: [true] } },
		description: '最初の失敗後にもう一度試す回数',
	},
	{
		displayName: '再試行までの待ち時間（ミリ秒）',
		name: 'retryDelay',
		type: 'number',
		default: 1000,
		typeOptions: { minValue: 100, maxValue: 30000 },
		displayOptions: { show: { retry: [true] } },
		description: '再試行するまでの待機時間',
	},
];

const stepValues: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'openUrl',
		options: [
			{ name: 'チェックを外す', value: 'uncheck' },
			{ name: 'チェックを入れる', value: 'check' },
			{ name: 'ファイルをアップロード', value: 'uploadFile' },
			{ name: 'プルダウンを選択', value: 'selectOption' },
			{ name: 'ページを開く', value: 'openUrl' },
			{ name: 'ボタンなどをクリック', value: 'click' },
			{ name: 'リンクを取得', value: 'getAttribute' },
			{ name: '画面の文字を取得', value: 'getText' },
			{ name: '画面をスクロール', value: 'scroll' },
			{ name: '画面を画像で保存', value: 'screenshot' },
			{ name: '指定した状態まで待つ', value: 'wait' },
			{ name: '文字を入力', value: 'fill' },
		],
	},
	{
		displayName: '開くページのURL',
		name: 'url',
		type: 'string',
		default: '',
		required: true,
		placeholder: '例: https://example.com/customer/new',
		displayOptions: { show: { operation: ['openUrl'] } },
	},
	{
		displayName: 'ページを開いた後の待ち方',
		name: 'waitUntil',
		type: 'options',
		default: 'load',
		displayOptions: { show: { operation: ['openUrl'] } },
		options: [
			{ name: 'ページ表示が完了するまで（おすすめ）', value: 'load' },
			{ name: '画面の骨組みができるまで（速い）', value: 'domcontentloaded' },
			{ name: '通信が落ち着くまで（時間がかかる場合あり）', value: 'networkidle' },
		],
	},
	{
		displayName: 'スクロール方法',
		name: 'scrollMode',
		type: 'options',
		default: 'distance',
		displayOptions: { show: { operation: ['scroll'] } },
		options: [
			{
				name: '追加データがなくなるまで繰り返す（無限スクロール）',
				value: 'infinite',
			},
			{ name: 'ページの最下部まで移動', value: 'bottom' },
			{ name: '指定した距離だけ移動', value: 'distance' },
			{ name: '指定した場所まで移動', value: 'element' },
		],
	},
	{
		displayName: '追加読み込みの確認方法',
		name: 'infiniteScrollDetection',
		type: 'options',
		default: 'pageHeight',
		displayOptions: { show: { operation: ['scroll'], scrollMode: ['infinite'] } },
		options: [
			{ name: 'ページの高さが増えるか確認（通常はこちら）', value: 'pageHeight' },
			{ name: '指定した場所の件数が増えるか確認', value: 'elementCount' },
		],
	},
	...locatorFields({ show: { operation: ['scroll'], scrollMode: ['element'] } }),
	...locatorFields({
		show: {
			operation: ['scroll'],
			scrollMode: ['infinite'],
			infiniteScrollDetection: ['elementCount'],
		},
	}),
	{
		displayName: 'スクロールする方向',
		name: 'scrollDirection',
		type: 'options',
		default: 'down',
		displayOptions: { show: { operation: ['scroll'], scrollMode: ['distance'] } },
		options: [
			{ name: '下へ', value: 'down' },
			{ name: '上へ', value: 'up' },
		],
	},
	{
		displayName: '移動する距離（ピクセル）',
		name: 'scrollDistance',
		type: 'number',
		default: 600,
		typeOptions: { minValue: 1, maxValue: 100000 },
		displayOptions: { show: { operation: ['scroll'], scrollMode: ['distance'] } },
	},
	{
		displayName: 'スクロール後に待つ時間（ミリ秒）',
		name: 'waitAfterScroll',
		type: 'number',
		default: 500,
		typeOptions: { minValue: 0, maxValue: 300000 },
		displayOptions: {
			show: { operation: ['scroll'], scrollMode: ['bottom', 'distance', 'element'] },
		},
		description: 'スクロール後に画面の表示が落ち着くまで待つ時間です',
	},
	{
		displayName: '最大スクロール回数',
		name: 'maximumScrolls',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 500 },
		displayOptions: { show: { operation: ['scroll'], scrollMode: ['infinite'] } },
		description: '無限ループを防ぐため、この回数に達した場合はエラーとして停止します',
	},
	{
		displayName: '1回ごとの待ち時間（ミリ秒）',
		name: 'scrollInterval',
		type: 'number',
		default: 1000,
		typeOptions: { minValue: 100, maxValue: 30000 },
		displayOptions: { show: { operation: ['scroll'], scrollMode: ['infinite'] } },
		description: '追加データが読み込まれるまで待つ時間です',
	},
	{
		displayName: '変化がない場合に終了する回数',
		name: 'unchangedScrollLimit',
		type: 'number',
		default: 2,
		typeOptions: { minValue: 1, maxValue: 10 },
		displayOptions: { show: { operation: ['scroll'], scrollMode: ['infinite'] } },
		description: '連続して変化しなかった回数がこの値に達すると、最下部まで到達したと判断します',
	},
	{
		displayName: '取得する範囲',
		name: 'textExtractionMode',
		type: 'options',
		default: 'single',
		displayOptions: { show: { operation: ['getText', 'getAttribute'] } },
		options: [
			{
				name: '1件だけ取得',
				value: 'single',
				description: '選択した1件の値を取得します',
			},
			{
				name: '表示されているすべてを一覧で取得',
				value: 'allVisible',
				description: '同じグループで画面に表示されている値を配列で取得します',
			},
		],
	},
	{
		displayName: '最大取得件数',
		name: 'maximumTextResults',
		type: 'number',
		default: 100,
		typeOptions: { minValue: 1, maxValue: 1000 },
		displayOptions: {
			show: { operation: ['getText', 'getAttribute'], textExtractionMode: ['allVisible'] },
		},
		description: '表示されている値を上から何件まで取得するかを指定します',
	},
	{
		displayName:
			'ブラウザで選ぶと、1件用と一覧用の指定を保存します。取得する範囲を後から切り替えても自動で使い分けます。',
		name: 'textExtractionPickerGuide',
		type: 'notice',
		default: '',
		displayOptions: { show: { operation: ['getText', 'getAttribute'] } },
	},
	{
		displayName: 'Picker Locator Variants',
		name: 'pickerLocatorVariants',
		type: 'hidden',
		default: '',
	},
	...locatorFields({ show: { operation: locatorOperations } }),
	...locatorFields({ show: { operation: ['click'] } }, 'クリックする種類'),
	...locatorFields({ show: { operation: ['screenshot'], screenshotTarget: ['element'] } }),
	...locatorFields({
		show: { operation: ['wait'], waitType: ['elementVisible', 'elementHidden'] },
	}),
	{
		displayName: '入力する文字',
		name: 'fillValue',
		type: 'string',
		default: '',
		displayOptions: { show: { operation: ['fill'] } },
		description: '固定の文字、または前のノードから受け取った値を入力できます',
	},
	{
		displayName: 'クリックを待つ最大時間（ミリ秒）',
		name: 'clickTimeout',
		type: 'number',
		default: 30000,
		typeOptions: { minValue: 1, maxValue: 300000 },
		displayOptions: { show: { operation: ['click'] } },
	},
	{
		displayName: 'クリック後に追加で待つ時間（ミリ秒）',
		name: 'waitAfterClick',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0, maxValue: 300000 },
		displayOptions: { show: { operation: ['click'] } },
		description:
			'通常は0のままにします。画面の変化を待つ場合は、次に「指定した状態まで待つ」を追加します',
	},
	{
		displayName: 'クリック後のページ切り替えを待つ',
		name: 'waitForNavigation',
		type: 'boolean',
		default: false,
		displayOptions: { show: { operation: ['click'] } },
	},
	{
		displayName:
			'この設定自体がページを切り替えることはありません。クリックによって別のページが読み込まれる場合だけ有効にします。',
		name: 'navigationWaitGuide',
		type: 'notice',
		default: '',
		displayOptions: { show: { operation: ['click'] } },
	},
	{
		displayName: '強制クリック（上級者向け）',
		name: 'forceClick',
		type: 'boolean',
		default: false,
		displayOptions: { show: { operation: ['click'] } },
	},
	{
		displayName: '選び方',
		name: 'selectBy',
		type: 'options',
		default: 'label',
		displayOptions: { show: { operation: ['selectOption'] } },
		options: [
			{ name: '画面に表示されている文字で選ぶ（おすすめ）', value: 'label' },
			{ name: 'HTMLの値で選ぶ（上級者向け）', value: 'value' },
			{ name: '上からの順番で選ぶ（上級者向け）', value: 'index' },
		],
	},
	{
		displayName: '選ぶ文字または値',
		name: 'selectValue',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { operation: ['selectOption'], selectBy: ['value', 'label'] } },
	},
	{
		displayName: '上から何番目か（0から数える）',
		name: 'selectIndex',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		displayOptions: { show: { operation: ['selectOption'], selectBy: ['index'] } },
	},
	{
		displayName: '何を待つか',
		name: 'waitType',
		type: 'options',
		default: 'time',
		displayOptions: { show: { operation: ['wait'] } },
		options: [
			{ name: 'URLが変わるまで', value: 'url' },
			{ name: 'テキストが表示されるまで', value: 'textAppears' },
			{ name: 'ページの読み込みが終わるまで', value: 'loadState' },
			{ name: '指定した時間だけ待つ', value: 'time' },
			{ name: '指定した場所が消えるまで', value: 'elementHidden' },
			{ name: '指定した場所が表示されるまで', value: 'elementVisible' },
		],
	},
	{
		displayName: '待機時間（ミリ秒）',
		name: 'waitTime',
		type: 'number',
		default: 1000,
		typeOptions: { minValue: 0, maxValue: 300000 },
		displayOptions: { show: { operation: ['wait'], waitType: ['time'] } },
	},
	{
		displayName: '表示を待つ文字',
		name: 'waitText',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { operation: ['wait'], waitType: ['textAppears'] } },
	},
	{
		displayName: '移動先URLの条件',
		name: 'waitUrl',
		type: 'string',
		default: '',
		required: true,
		placeholder: '例: **/complete',
		displayOptions: { show: { operation: ['wait'], waitType: ['url'] } },
	},
	{
		displayName: 'どこまで読み込むか',
		name: 'loadState',
		type: 'options',
		default: 'load',
		displayOptions: { show: { operation: ['wait'], waitType: ['loadState'] } },
		options: [
			{ name: 'ページ表示が完了するまで（おすすめ）', value: 'load' },
			{ name: '画面の骨組みができるまで（速い）', value: 'domcontentloaded' },
			{ name: '通信が落ち着くまで（時間がかかる場合あり）', value: 'networkidle' },
		],
	},
	{
		displayName: '待つ最大時間（ミリ秒）',
		name: 'waitTimeout',
		type: 'number',
		default: 30000,
		typeOptions: { minValue: 1, maxValue: 300000 },
		displayOptions: {
			show: {
				operation: ['wait'],
				waitType: ['elementVisible', 'elementHidden', 'textAppears', 'url', 'loadState'],
			},
		},
	},
	{
		displayName: '取得結果の名前',
		name: 'outputVariableName',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'registrationNumberなど',
		displayOptions: { show: { operation: ['getText', 'getAttribute'] } },
		description: '後続ノードから取得結果を使うときの名前。半角英数字で分かりやすい名前を付けます',
	},
	{
		displayName: 'アップロードするファイルの受取元名',
		name: 'uploadBinaryProperty',
		type: 'string',
		default: 'data',
		required: true,
		displayOptions: { show: { operation: ['uploadFile'] } },
		description: '前のノードから受け取ったファイルの名前。通常はdataのままにします',
	},
	{
		displayName: '画像にする範囲',
		name: 'screenshotTarget',
		type: 'options',
		default: 'viewport',
		displayOptions: { show: { operation: ['screenshot'] } },
		options: [
			{ name: '現在見えている範囲', value: 'viewport' },
			{ name: 'ページ全体', value: 'fullPage' },
			{ name: '指定した場所だけ', value: 'element' },
		],
	},
	{
		displayName: '画像形式',
		name: 'imageFormat',
		type: 'options',
		default: 'png',
		displayOptions: { show: { operation: ['screenshot'] } },
		options: [
			{ name: 'PNG', value: 'png' },
			{ name: 'JPEG', value: 'jpeg' },
		],
	},
	{
		displayName: 'JPEG画質（1～100）',
		name: 'jpegQuality',
		type: 'number',
		default: 80,
		typeOptions: { minValue: 1, maxValue: 100 },
		displayOptions: { show: { operation: ['screenshot'], imageFormat: ['jpeg'] } },
	},
	{
		displayName: '画像の保存先名',
		name: 'screenshotBinaryProperty',
		type: 'string',
		default: 'screenshot',
		required: true,
		displayOptions: { show: { operation: ['screenshot'] } },
	},
	...retryFields,
];

export const browserAutomationProperties: INodeProperties[] = [
	{
		displayName: 'ブラウザ画面を表示せずに実行',
		name: 'headless',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '実行後すぐブラウザを閉じる',
		name: 'closeBrowserImmediately',
		type: 'boolean',
		default: false,
		displayOptions: { show: { headless: [false] } },
	},
	{
		displayName: '実行後に画面を残す時間（ミリ秒）',
		name: 'browserCloseDelay',
		type: 'number',
		default: 30000,
		typeOptions: { minValue: 1000, maxValue: 300000 },
		displayOptions: { show: { headless: [false], closeBrowserImmediately: [false] } },
		description: '手動実行の成功画面またはエラー内容を表示してからブラウザを閉じるまでの時間',
	},
	{
		displayName: 'ブラウザの詳細設定（通常は変更不要）',
		name: 'browserSettings',
		type: 'collection',
		placeholder: '詳細設定を追加',
		default: {},
		options: [
			{
				displayName: 'ブラウザ起動を待つ最大時間（ミリ秒）',
				name: 'browserTimeout',
				type: 'number',
				default: 30000,
				typeOptions: { minValue: 1000, maxValue: 300000 },
			},
			{
				displayName: 'ページ移動を待つ最大時間（ミリ秒）',
				name: 'navigationTimeout',
				type: 'number',
				default: 30000,
				typeOptions: { minValue: 1000, maxValue: 300000 },
			},
			{
				displayName: '表示領域の幅',
				name: 'viewportWidth',
				type: 'number',
				default: 1280,
				typeOptions: { minValue: 320, maxValue: 7680 },
			},
			{
				displayName: '表示領域の高さ',
				name: 'viewportHeight',
				type: 'number',
				default: 720,
				typeOptions: { minValue: 240, maxValue: 4320 },
			},
			{
				displayName: 'ブラウザの識別情報（上級者向け）',
				name: 'userAgent',
				type: 'string',
				default: '',
			},
			{
				displayName: '表示言語と地域',
				name: 'locale',
				type: 'string',
				default: 'ja-JP',
			},
			{
				displayName: 'タイムゾーン',
				name: 'timezone',
				type: 'string',
				default: 'Asia/Tokyo',
			},
			{
				displayName: 'HTTPS証明書エラーを無視（非推奨）',
				name: 'ignoreHttpsErrors',
				type: 'boolean',
				default: false,
			},
			{
				displayName: '社内ネットワークやLocalhostへのアクセスを許可',
				name: 'allowPrivateNetwork',
				type: 'boolean',
				default: false,
			},
			{
				displayName: '1ファイルの最大サイズ（MB）',
				name: 'maxUploadSizeMb',
				type: 'number',
				default: 25,
				typeOptions: { minValue: 1, maxValue: 100 },
			},
		],
	},
	{
		displayName:
			'ステップを追加し、上から順に操作を設定します。例：ページを開く → 文字を入力 → ボタンをクリック → 画面の文字を取得',
		name: 'beginnerGuide',
		type: 'notice',
		default: '',
	},
	{
		displayName: 'ブラウザで行う操作',
		name: 'steps',
		type: 'fixedCollection',
		placeholder: '操作を追加',
		typeOptions: { multipleValues: true, sortable: true },
		default: { step: [] },
		required: true,
		options: [
			{
				displayName: '操作',
				name: 'step',
				values: stepValues,
			},
		],
	},
	{
		displayName: 'エラーが発生したとき',
		name: 'errorBehavior',
		type: 'options',
		default: 'output',
		options: [
			{
				name: 'エラー内容を出力して続ける（おすすめ）',
				value: 'output',
				description: 'エラー内容を「エラー」出力へ送り、次の入力データを処理します',
			},
			{
				name: 'ワークフローを停止',
				value: 'throw',
				description: 'この操作でエラーが発生した時点でワークフローを停止します',
			},
		],
	},
	{
		displayName: 'エラー時の画面を画像で保存',
		name: 'captureScreenshotOnError',
		type: 'boolean',
		default: false,
	},
	{
		displayName: 'エラー画像の保存先名',
		name: 'errorScreenshotBinaryProperty',
		type: 'string',
		default: 'errorScreenshot',
		required: true,
		displayOptions: { show: { captureScreenshotOnError: [true] } },
	},
	{
		displayName: '詳しい実行記録を出力（上級者向け）',
		name: 'debugMode',
		type: 'boolean',
		default: false,
	},
];
