import type { INodeProperties } from 'n8n-workflow';

const locatorOperations = [
	'fill',
	'click',
	'selectOption',
	'check',
	'uncheck',
	'getText',
	'getAttribute',
	'uploadFile',
];

const roleOptions = [
	{ name: 'ボタン', value: 'button' },
	{ name: 'チェックボックス', value: 'checkbox' },
	{ name: 'コンボボックス', value: 'combobox' },
	{ name: '見出し', value: 'heading' },
	{ name: '画像', value: 'img' },
	{ name: 'リンク', value: 'link' },
	{ name: 'リスト項目', value: 'listitem' },
	{ name: '選択肢', value: 'option' },
	{ name: 'ラジオボタン', value: 'radio' },
	{ name: 'タブ', value: 'tab' },
	{ name: 'テキストボックス', value: 'textbox' },
];

function locatorFields(
	displayOptions: NonNullable<INodeProperties['displayOptions']>,
): INodeProperties[] {
	return [
		{
			displayName: 'ロケーターの種類',
			name: 'locatorType',
			type: 'options',
			default: 'label',
			displayOptions,
			options: [
				{
					name: 'CSS（上級者向け）',
					value: 'css',
					description: 'CSSセレクターで要素を指定します',
				},
				{ name: 'XPath（上級者向け）', value: 'xpath', description: 'XPathで要素を指定します' },
				{ name: 'テキスト', value: 'text', description: '画面に表示される文字で要素を指定します' },
				{ name: 'テストID', value: 'testId', description: 'テストID属性で要素を指定します' },
				{
					name: 'プレースホルダー',
					value: 'placeholder',
					description: 'プレースホルダーで入力項目を指定します',
				},
				{ name: 'ラベル', value: 'label', description: 'ラベルで入力項目を指定します' },
				{
					name: 'ロール',
					value: 'role',
					description: 'ARIAロールとアクセシブル名で要素を指定します',
				},
			],
		},
		{
			displayName: 'ロール',
			name: 'locatorRole',
			type: 'options',
			default: 'button',
			options: roleOptions,
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: ['role'],
				},
			},
		},
		{
			displayName: 'アクセシブル名',
			name: 'locatorName',
			type: 'string',
			default: '',
			required: true,
			placeholder: '例: 登録',
			description: '選択したロールを持つ要素のアクセシブル名',
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: ['role'],
				},
			},
		},
		{
			displayName: 'ロケーターの値',
			name: 'locatorValue',
			type: 'string',
			default: '',
			required: true,
			placeholder: '例: 顧客名',
			description: 'ラベル、プレースホルダー、テキスト、テストID、CSS、またはXPath',
			displayOptions: {
				show: {
					...displayOptions.show,
					locatorType: ['label', 'placeholder', 'text', 'testId', 'css', 'xpath'],
				},
			},
		},
		{
			displayName: 'フレーム',
			name: 'frameType',
			type: 'options',
			default: 'none',
			displayOptions,
			options: [
				{ name: '指定なし', value: 'none' },
				{ name: 'フレーム名で指定', value: 'name' },
				{ name: 'URLで指定', value: 'url' },
				{ name: 'CSSで指定（上級者向け）', value: 'css' },
			],
		},
		{
			displayName: 'フレームの値',
			name: 'frameValue',
			type: 'string',
			default: '',
			required: true,
			placeholder: '例: customer-frame',
			description: 'フレームのname属性、URLの一部、またはCSSセレクター',
			displayOptions: {
				show: {
					...displayOptions.show,
					frameType: ['name', 'url', 'css'],
				},
			},
		},
	];
}

const retryFields: INodeProperties[] = [
	{
		displayName: '一時エラーを再試行',
		name: 'retry',
		type: 'boolean',
		default: false,
	},
	{
		displayName: '最大再試行回数',
		name: 'maxRetries',
		type: 'number',
		default: 2,
		typeOptions: { minValue: 1, maxValue: 5 },
		displayOptions: { show: { retry: [true] } },
		description: '最初の実行に失敗した後で再試行する最大回数',
	},
	{
		displayName: '再試行間隔（ミリ秒）',
		name: 'retryDelay',
		type: 'number',
		default: 1000,
		typeOptions: { minValue: 100, maxValue: 30000 },
		displayOptions: { show: { retry: [true] } },
		description: '再試行するまでの待機時間',
	},
];

const stepValues: INodeProperties[] = [
	{
		displayName: '操作',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'openUrl',
		options: [
			{ name: 'URLを開く', value: 'openUrl' },
			{ name: 'クリック', value: 'click' },
			{ name: 'スクリーンショット', value: 'screenshot' },
			{ name: 'チェック', value: 'check' },
			{ name: 'チェックを外す', value: 'uncheck' },
			{ name: 'テキストを取得', value: 'getText' },
			{ name: 'ファイルをアップロード', value: 'uploadFile' },
			{ name: '選択肢を選択', value: 'selectOption' },
			{ name: '属性を取得', value: 'getAttribute' },
			{ name: '待機', value: 'wait' },
			{ name: '入力', value: 'fill' },
		],
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		default: '',
		required: true,
		placeholder: '例: https://example.com/customer/new',
		displayOptions: { show: { operation: ['openUrl'] } },
	},
	{
		displayName: '読み込み待機',
		name: 'waitUntil',
		type: 'options',
		default: 'load',
		displayOptions: { show: { operation: ['openUrl'] } },
		options: [
			{ name: '読み込み完了', value: 'load' },
			{ name: 'DOM構築完了', value: 'domcontentloaded' },
			{ name: '通信が落ち着くまで', value: 'networkidle' },
		],
	},
	...locatorFields({ show: { operation: locatorOperations } }),
	...locatorFields({ show: { operation: ['screenshot'], screenshotTarget: ['element'] } }),
	...locatorFields({
		show: { operation: ['wait'], waitType: ['elementVisible', 'elementHidden'] },
	}),
	{
		displayName: '入力値',
		name: 'fillValue',
		type: 'string',
		default: '',
		displayOptions: { show: { operation: ['fill'] } },
		description: '指定した入力項目へ設定する値。Expressionを利用できます',
	},
	{
		displayName: 'タイムアウト（ミリ秒）',
		name: 'clickTimeout',
		type: 'number',
		default: 30000,
		typeOptions: { minValue: 1, maxValue: 300000 },
		displayOptions: { show: { operation: ['click'] } },
	},
	{
		displayName: 'クリック後の待機時間（ミリ秒）',
		name: 'waitAfterClick',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0, maxValue: 300000 },
		displayOptions: { show: { operation: ['click'] } },
		description:
			'クリック後に固定時間だけ待機します。可能な場合は状態を指定した待機ステップを使ってください',
	},
	{
		displayName: 'ページ遷移を待つ',
		name: 'waitForNavigation',
		type: 'boolean',
		default: false,
		displayOptions: { show: { operation: ['click'] } },
	},
	{
		displayName: '強制クリック（上級者向け）',
		name: 'forceClick',
		type: 'boolean',
		default: false,
		displayOptions: { show: { operation: ['click'] } },
	},
	{
		displayName: '選択方法',
		name: 'selectBy',
		type: 'options',
		default: 'value',
		displayOptions: { show: { operation: ['selectOption'] } },
		options: [
			{ name: '値', value: 'value' },
			{ name: 'ラベル', value: 'label' },
			{ name: 'インデックス', value: 'index' },
		],
	},
	{
		displayName: '選択肢の値',
		name: 'selectValue',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { operation: ['selectOption'], selectBy: ['value', 'label'] } },
	},
	{
		displayName: '選択肢のインデックス',
		name: 'selectIndex',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		displayOptions: { show: { operation: ['selectOption'], selectBy: ['index'] } },
	},
	{
		displayName: '待機条件',
		name: 'waitType',
		type: 'options',
		default: 'elementVisible',
		displayOptions: { show: { operation: ['wait'] } },
		options: [
			{ name: 'URL', value: 'url' },
			{ name: 'テキストが表示されるまで', value: 'textAppears' },
			{ name: '指定時間', value: 'time' },
			{ name: '読み込み状態', value: 'loadState' },
			{ name: '要素が非表示になるまで', value: 'elementHidden' },
			{ name: '要素が表示されるまで', value: 'elementVisible' },
		],
	},
	{
		displayName: '待機時間（ミリ秒）',
		name: 'waitTime',
		type: 'number',
		default: 1000,
		typeOptions: { minValue: 0, maxValue: 300000 },
		displayOptions: { show: { operation: ['wait'], waitType: ['time'] } },
	},
	{
		displayName: 'テキスト',
		name: 'waitText',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { operation: ['wait'], waitType: ['textAppears'] } },
	},
	{
		displayName: '待機するURL',
		name: 'waitUrl',
		type: 'string',
		default: '',
		required: true,
		placeholder: '例: **/complete',
		displayOptions: { show: { operation: ['wait'], waitType: ['url'] } },
	},
	{
		displayName: '読み込み状態',
		name: 'loadState',
		type: 'options',
		default: 'load',
		displayOptions: { show: { operation: ['wait'], waitType: ['loadState'] } },
		options: [
			{ name: '読み込み完了', value: 'load' },
			{ name: 'DOM構築完了', value: 'domcontentloaded' },
			{ name: '通信が落ち着くまで', value: 'networkidle' },
		],
	},
	{
		displayName: 'タイムアウト（ミリ秒）',
		name: 'waitTimeout',
		type: 'number',
		default: 30000,
		typeOptions: { minValue: 1, maxValue: 300000 },
		displayOptions: {
			show: {
				operation: ['wait'],
				waitType: ['elementVisible', 'elementHidden', 'textAppears', 'url', 'loadState'],
			},
		},
	},
	{
		displayName: '出力変数名',
		name: 'outputVariableName',
		type: 'string',
		default: '',
		required: true,
		placeholder: '例: registrationNumber',
		displayOptions: { show: { operation: ['getText', 'getAttribute'] } },
		description: '取得した値を後続ノードから参照するためのトップレベルJSONフィールド名',
	},
	{
		displayName: '属性名',
		name: 'attributeName',
		type: 'string',
		default: 'href',
		required: true,
		displayOptions: { show: { operation: ['getAttribute'] } },
	},
	{
		displayName: '入力Binaryフィールド',
		name: 'uploadBinaryProperty',
		type: 'string',
		default: 'data',
		required: true,
		displayOptions: { show: { operation: ['uploadFile'] } },
		description: 'アップロードするファイルが入っている入力Binaryフィールド名',
	},
	{
		displayName: '撮影範囲',
		name: 'screenshotTarget',
		type: 'options',
		default: 'viewport',
		displayOptions: { show: { operation: ['screenshot'] } },
		options: [
			{ name: '表示領域', value: 'viewport' },
			{ name: 'ページ全体', value: 'fullPage' },
			{ name: '要素', value: 'element' },
		],
	},
	{
		displayName: '画像形式',
		name: 'imageFormat',
		type: 'options',
		default: 'png',
		displayOptions: { show: { operation: ['screenshot'] } },
		options: [
			{ name: 'PNG', value: 'png' },
			{ name: 'JPEG', value: 'jpeg' },
		],
	},
	{
		displayName: 'JPEG画質',
		name: 'jpegQuality',
		type: 'number',
		default: 80,
		typeOptions: { minValue: 1, maxValue: 100 },
		displayOptions: { show: { operation: ['screenshot'], imageFormat: ['jpeg'] } },
	},
	{
		displayName: '出力Binaryフィールド',
		name: 'screenshotBinaryProperty',
		type: 'string',
		default: 'screenshot',
		required: true,
		displayOptions: { show: { operation: ['screenshot'] } },
	},
	...retryFields,
];

export const browserAutomationProperties: INodeProperties[] = [
	{
		displayName: 'ブラウザ設定',
		name: 'browserSettings',
		type: 'collection',
		placeholder: '設定を追加',
		default: {},
		options: [
			{
				displayName: 'ヘッドレス',
				name: 'headless',
				type: 'boolean',
				default: true,
			},
			{
				displayName: 'ブラウザ起動タイムアウト（ミリ秒）',
				name: 'browserTimeout',
				type: 'number',
				default: 30000,
				typeOptions: { minValue: 1000, maxValue: 300000 },
			},
			{
				displayName: 'ページ遷移タイムアウト（ミリ秒）',
				name: 'navigationTimeout',
				type: 'number',
				default: 30000,
				typeOptions: { minValue: 1000, maxValue: 300000 },
			},
			{
				displayName: '表示領域の幅',
				name: 'viewportWidth',
				type: 'number',
				default: 1280,
				typeOptions: { minValue: 320, maxValue: 7680 },
			},
			{
				displayName: '表示領域の高さ',
				name: 'viewportHeight',
				type: 'number',
				default: 720,
				typeOptions: { minValue: 240, maxValue: 4320 },
			},
			{
				displayName: 'ユーザーエージェント',
				name: 'userAgent',
				type: 'string',
				default: '',
			},
			{
				displayName: 'ロケール',
				name: 'locale',
				type: 'string',
				default: 'ja-JP',
			},
			{
				displayName: 'タイムゾーン',
				name: 'timezone',
				type: 'string',
				default: 'Asia/Tokyo',
			},
			{
				displayName: 'HTTPSエラーを無視',
				name: 'ignoreHttpsErrors',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'プライベートネットワークURLを許可（信頼済みサイトのみ）',
				name: 'allowPrivateNetwork',
				type: 'boolean',
				default: false,
			},
			{
				displayName: '最大アップロードサイズ (MB)',
				name: 'maxUploadSizeMb',
				type: 'number',
				default: 25,
				typeOptions: { minValue: 1, maxValue: 100 },
			},
		],
	},
	{
		displayName: 'ステップ',
		name: 'steps',
		type: 'fixedCollection',
		placeholder: 'ステップを追加',
		typeOptions: { multipleValues: true, sortable: true },
		default: { step: [] },
		required: true,
		options: [
			{
				displayName: 'ステップ',
				name: 'step',
				values: stepValues,
			},
		],
	},
	{
		displayName: 'エラー時の動作',
		name: 'errorBehavior',
		type: 'options',
		default: 'output',
		options: [
			{
				name: 'エラーデータを出力',
				value: 'output',
				description: '構造化されたエラーを「エラー」出力へ送り、残りのItemを処理します',
			},
			{
				name: 'ワークフローを停止',
				value: 'throw',
				description:
					'「失敗しても処理を続行」が有効でない場合、n8nエラーとしてワークフローを停止します',
			},
		],
	},
	{
		displayName: 'エラー時にスクリーンショットを取得',
		name: 'captureScreenshotOnError',
		type: 'boolean',
		default: false,
	},
	{
		displayName: 'エラースクリーンショットのBinaryフィールド',
		name: 'errorScreenshotBinaryProperty',
		type: 'string',
		default: 'errorScreenshot',
		required: true,
		displayOptions: { show: { captureScreenshotOnError: [true] } },
	},
	{
		displayName: 'デバッグモード',
		name: 'debugMode',
		type: 'boolean',
		default: false,
	},
];
